services:
   wordpress_app:
     container_name: wordpress_app
     image: wordpress:latest
     restart: unless-stopped
     ports:
       - '8080:80' 
     environment:
       WORDPRESS_DB_HOST: wordpress_db 
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
     depends_on:
       - wordpress_db
     volumes:
       - wordpress_files:/var/www/html

   wordpress_db:
     container_name: wordpress_db
     image: mysql:latest
     restart: unless-stopped
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     volumes:
       - db_data:/var/lib/mysql

volumes:
    wordpress_files:
    db_data:
