services:
   wordpress_app:
     container_name: wordpress_app
     image: wordpress:latest
     restart: always
     ports:
       - '8081:80'
     environment:
       WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
       WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
       WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
       WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}

     depends_on:
       - wordpress_db
     volumes:
       - wordpress_files:/var/www/html

   wordpress_db:
     container_name: wordpress_db
     image: mysql:latest
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
     volumes:
       - db_data:/var/lib/mysql

volumes:
    wordpress_files:
    db_data:
